# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7c30f88174c207032f3d89f5d6835340ff5c34b4895ba5a1e9d86e0f99d44368e06b6142cfaa2748ce48a89e6a27ec2411701964e099bd5c9e72fa2b06908c98

test:
  secret_key_base: 1e5922947d6c41c7728b93592c77167bda311e4ccb4df3572373616b7c5a72ce863107e49445ba84ade060730fa20750fe779b060f80c05d2004c07bbd59574d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
